---
# K3s server configuration
k3s_version: latest

# Additional server flags
k3s_server_flags: ""

# Disable built-in components
k3s_disable_traefik: true
k3s_disable_servicelb: true

# Cluster configuration
k3s_cluster_init: true
